{/* Check which Fallout game we have. Goes in Top Shelf Locker B */}
{/* Figure out what "born" is in Locker C 4th Shelf */}
{/* Figure out what "Castles of Burgundy" is in Locker E 2nd Shelf */}

const games_database = [
    {
        imagePath: "./src/assets/gamePhotos/5minuteDungeon.jpeg",
        title: "5-Minute Dungeon",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/7wonders.webp",
        title: "7 Wonders",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/7wondersDuel.jpeg",
        title: "7 Wonders: Duel",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/7wondersDuelPantheon.avif",
        title: "7 Wonders: Duel Pantheon",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/aboveAndBelow.jpeg",
        title: "Above and Below",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/agathaChristiesDeathOnTheCards.jpeg",
        title: "Agatha Christie's Death on the Cards",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/agricola.jpeg",
        title: "Agricola",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/airLandAndSeaCrittersAtWar.jpeg",
        title: "Air, Land, and Sea Critters at War",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/alhambra.jpeg",
        title: "Alhambra",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/alienFrontiers.webp",
        title: "Alien Frontiers",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/amerigo.jpeg",
        title: "Amerigo",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/amongTheStars.png",
        title: "Among The Stars",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/amunRe.webp",
        title: "Amun-Re",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/anachrony.jpeg",
        title: "Anachrony",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/applesToApples.jpeg",
        title: "Apples to Apples",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/arboretum.jpeg",
        title: "Arboretum",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/architectsOfTheWestKingdom.jpeg",
        title: "Architects of the West Kingdom",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/arcs.webp",
        title: "Arcs",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkhamHorror.webp",
        title: "Arkham Horror",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkhamHorrorDunwich.jpeg",
        title: "Arkham Horror: The Dunwich Legacy",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkNova.jpeg",
        title: "Ark Nova",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkNovaMarineWorlds.jpeg",
        title: "Ark Nova: Marine Worlds",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/automobiles.png",
        title: "Automobiles",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/avalon.jpeg",
        title: "Avalon",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/azul.jpeg",
        title: "Azul",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/azulSummerPavillion.webp",
        title: "Azul: Summer Pavillion",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/bananagrams.png",
        title: "Bananagrams",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/baseballHighlights2045.webp",
        title: "Baseball Highlights 2045",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/battlestarGalactica.jpeg",
        title: "Battlestar Galactica",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/betrayalAtHouseOnTheHill.jpeg",
        title: "Betrayal at House on the Hill",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/betweenTwoCastlesOfMadKingLudwig.jpeg",
        title: "Between Two Castles of Mad King Ludwig",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/betweenTwoCities.png",
        title: "Between Two Cities",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/bloodborneTheCardGame.jpeg",
        title: "Bloodborne: The Card Game",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    { 
        imagePath: "./src/assets/gamePhotos/bloodOnTheClocktower.jpeg",
        title: "Blood on the Clocktower",
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/bloodRage.webp",
        title: "Blood Rage",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bobRossArtOfChillGame.jpeg",
        title: "Bob Ross: Art of Chill Game",
        description: "TBA",
        storageLocation: "Top Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/bohnanza.jpeg",
        title: "Bohnanza",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/brassBirmingham.jpeg",
        title: "Brass: Birmingham",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/brassLancashire.jpeg",
        title: "Brass: Lancashire",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/bulletStar.jpeg",
        title: "Bullet Star",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bunnyKingdom.jpeg",
        title: "Bunny Kingdom",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bunnyKingdomInTheSky.webp",
        title: "Bunny Kingdom in the Sky",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/burgleBros.jpeg",
        title: "Burgle Bros.",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/calico.jpeg",
        title: "Calico",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/canvas.jpeg",
        title: "Canvas",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/captainSonar.webp",
        title: "Captain Sonar",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/carcassonne.webp",
        title: "Carcassonne",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/cascadia.jpeg",
        title: "Cascadia",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/castlesOfMadKingLudwig.jpeg",
        title: "Castles of Mad King Ludwig",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/catan.webp",
        title: "Catan",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/catanStarfarers.png",
        title: "Catan Starfarers",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/catInTheBox.webp",
        title: "Cat In The Box",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/championsOfMidgard.webp",
        title: "Champions of Midgard",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/chess.jpeg",
        title: "Chess",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/citiesOfSplendor.jpeg",
        title: "Cities of Splendor",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cityOfGears.jpeg", 
        title: "City of gears", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cityOfIron.jpeg", 
        title: "City of Iron", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/clank.jpeg", 
        title: "Clank!", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/clue.jpeg",
        title: "Clue",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/cockroachPoker.jpeg",
        title: "Cockroach Poker",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/Codenames.webp",
        title: "Codenames",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/concept.jpeg", 
        title: "Concept", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/concordia.jpeg",
        title: "Concordia",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cosmicEncounter.jpeg", 
        title: "Cosmic Encounter", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/coup.jpeg",
        title: "Coup",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/cryptid.jpeg",
        title: "Cryptid",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    {
        imagePath: "./src/assets/gamePhotos/cthulhuWars.jpeg",
        title: "Cthulhu Wars",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/cthulhuWarsTchoTcho.webp",
        title: "Cthulhu Wars: Tcho Tcho",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/cyclades.jpeg",
        title: "Cyclades",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/darkestNight.webp",
        title: "Darkest Night",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    { 
        imagePath: "./src/assets/gamePhotos/daybreak.jpeg", 
        title: "Daybreak", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/deadOfWinter.webp", 
        title: "Dead of Winter", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/deckOfCards.jpeg",
        title: "Decks of Cards",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/decorum.jpeg", 
        title: "Décorum", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/diceCity.jpeg",
        title: "Dice City",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/diceForge.jpeg",
        title: "Dice Forge",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/dinosaurIsland.jpeg", 
        title: "Dinosaur Island", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/dixitOdyssey.png", 
        title: "Dixit: Odyssey", 
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/dominion.webp",
        title: "Dominion",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionAllies.jpeg",
        title: "Dominion: Allies",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionDarkAges.jpeg",
        title: "Dominion: Dark Ages",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionSeaside.webp",
        title: "Dominion: Seaside",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dontBreakTheIce.avif",
        title: "Don't Break the Ice",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/dune.webp", 
        title: "Dune", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/duneImperium.jpeg", 
        title: "Dune: Imperium", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/eclipse.jpeg",
        title: "Eclipse",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/eldritchHorror.jpeg",
        title: "Eldritch Horror",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left"
    },
    {
        imagePath: "./src/assets/gamePhotos/eldritchHorrorMountainsOfMadness.png",
        title: "Eldritch Horror: Mountains of Madness",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left"
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdell.jpeg", 
        title: "Everdell", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdellBellfaire.jpeg", 
        title: "Everdell: Bellfaire", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdellNewLeaf.jpeg", 
        title: "Everdell: New Leaf", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/evolution.jpeg", 
        title: "Evolution", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/explodingKittens.jpeg", 
        title: "Exploding Kittens", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/fitToPrint.jpeg",
        title: "Fit to Print",
        description: "TBA",
        storageLocation: "2nd Shelf Locker E",
    },
    { 
        imagePath: "./src/assets/gamePhotos/forestShuffle.webp", 
        title: "Forest Shuffle", 
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/fromage.jpeg",
        title: "Fromage", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/funemployed.jpeg", 
        title: "Funemployed", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/furyOfDracula.webp", 
        title: "Fury of Dracula", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/fuse.jpeg",
        title: "Fuse",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/gameOfThrones.webp", 
        title: "Game of Thrones", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/go.jpeg",
        title: "Go",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/gonutsForDonuts.jpeg",
        title: "Gonuts for Donuts",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/hanabi.jpeg", 
        title: "Hanabi", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/harmonies.jpeg",
        title: "Harmonies",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/heat.jpeg", 
        title: "Heat: Pedal to the Metal", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/horizonsOfSpiritIsland.jpeg",
        title: "Horizons of Spirit Island",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/horselessCarriage.webp",
        title: "Horseless Carriage",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/hyperborea.jpeg",
        title: "Hyperborea",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/iceCool.jpeg",
        title: "Ice Cool",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/iceCool2.jpeg",
        title: "Ice Cool 2",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/incanGold.png",
        title: "Incan Gold",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/jenga.jpeg",
        title: "Jenga",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/jungleSpeed.jpeg",
        title: "Jungle Speed",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/justOne.jpeg",
        title: "Just One",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/kingdomino.jpeg",
        title: "Kingdomino",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/kyotoMoneyMakesTheWorldGoDown.jpeg",
        title: "Kyoto: Money Makes the World Go Down",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/lanternsTheHarvestFestival.jpeg",
        title: "Lanterns: The Harvest Festival",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/lemonadeStand.jpeg",
        title: "Lemonade Stand",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/letterJam.jpeg",
        title: "Letter Jam",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/lettersFromWhitechapel.png", 
        title: "Letters from Whitechapel", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/liarsDice.jpeg",
        title: "Liar's Dice",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/libertalia.webp", 
        title: "Libertalia", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/lostCities.jpeg",
        title: "Lost Cities",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/lostRuinsOfArnak.jpeg",
        title: "Lost Ruins of Arnak",
        description: "TBA",
        storageLocation: "Top Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/loveLetterPrincessPrincessEverAfter.jpeg",
        title: "Love Letter: Princess Princess Ever After",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/mageKnight.webp",
        title: "Mage Knight",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/memoir44.webp",
        title: "Memoir '44",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/miceAndMystics.webp",
        title: "Mice & Mystics",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/monopolyCheatersEdition.jpeg",
        title: "Monopoly: Cheater's Edition",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/monopolyScoobyDooEdition.jpeg",
        title: "Monopoly: Scooby-Doo Edition",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/myFathersWork.jpeg",
        title: "My Father's Work",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/mysterium.jpeg", 
        title: "Mysterium", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/mysticPaths.jpeg",
        title: "Mystic Paths",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/nertz.jpeg",
        title: "Nertz",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/noThanks.jpeg",
        title: "No Thanks!",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/oceans.jpeg",
        title: "Oceans",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/oneNightUltimateWerewolf.webp",
        title: "One Night Ultimate Werewolf",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/pandemicIberia.jpeg",
        title: "Pandemic: Iberia",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/pandemicOnTheBrink.webp",
        title: "Pandemic: On the brink",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/paranormalDetectives.jpeg",
        title: "Paranormal Detectives",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/parks.webp",
        title: "Parks",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/patchwork.jpeg",
        title: "Patchwork",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/pennyPress.avif",
        title: "Penny Press",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/planes.jpeg",
        title: "Planes",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/planet.jpeg",
        title: "Planet",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/potionExplosion.png",
        title: "Potion Explosion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/powerGrid.jpeg",
        title: "Power Grid",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/puertoRico.jpeg",
        title: "Puerto Rico",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/quoridor.jpeg",
        title: "Quoridor",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/raidersOfTheNorthSea.jpeg",
        title: "Raiders of the North Sea",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/railroadInkChallenge.png",
        title: "Railroad Ink Challenge",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/railwaysOfTheWorld.jpeg",
        title: "Railways of the World",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/raiseYourGoblets.jpeg",
        title: "Raise Your Goblets",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/redRising.jpeg",
        title: "Red Rising",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/rollForTheGalaxy.png",
        title: "Roll for the Galaxy",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/root.webp",
        title: "Root",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/rootTheMarauderExpansion.webp",
        title: "Root: The Marauder Expansion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/rootTheRiverfolkExpansion.webp",
        title: "Root: The Riverfolk Expansion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/rootTheUnderworldExpansion.webp",
        title: "Root: The Underworld Expansion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/saboteur.jpeg", 
        title: "Saboteur", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/santorini.jpeg",
        title: "Santorini",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/scoobyDooBetrayalAtMysteryMansion.jpeg",
        title: "Scooby-Doo! Betrayal at Mystery Mansion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/scoobyDooHideAndShriekGame.webp",
        title: "Scooby-Doo! Hide and Shriek Game",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/scoobyDooThrillsAndSpillsGame.jpeg",
        title: "Scooby-Doo! Thrills and Spills Game",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/Scout.jpeg", 
        title: "Scout", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/scoville.webp", 
        title: "Scoville", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/set.webp", 
        title: "Set", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/shadowsOverCamelot.webp",
        title: "Shadows Over Camelot",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F"
    },
    { 
        imagePath: "./src/assets/gamePhotos/sheriffOfNottingham.webp", 
        title: "Sheriff of Nottingham", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/shogi.jpeg",
        title: "Shogi",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/skull.jpeg",
        title: "Skull",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/slayTheSpire.jpeg", 
        title: "Slay the Spire", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/smallworld.jpeg",
        title: "Smallworld",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/smallworldUnderground.jpeg",
        title: "Smallworld: Underground",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/snollygoster.jpeg",
        title: "Snollygoster",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/soClover.jpeg",
        title: "So Clover",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/specterOps.jpeg",
        title: "Specter Ops",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/spiritIsland.webp",
        title: "Spirit Island", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/spiritIslandFeatherAndFlame.webp",
        title: "Spirit Island: Feather and Flame",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/spiritIslandJaggedEarth.jpeg",
        title: "Spirit Island: Jagged Earth",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/splendor.jpeg",
        title: "Splendor",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/spyfall.webp",
        title: "Spyfall",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/stardewValley.jpeg",
        title: "Stardew Valley",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/starWarsRebellion.jpeg",
        title: "Star Wars Rebellion",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/subdivision.webp",
        title: "Subdivision",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/suburbia.jpeg",
        title: "Suburbia",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/sushiGo.png", 
        title: "Sushi Go!", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/sushiGoParty.webp",
        title: "Sushi Go Party!",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/sythe.webp", 
        title: "Sythe", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/takenoko.jpeg",
        title: "Takenoko",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMars.jpeg",
        title: "Terraforming Mars",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMarsAresExpedition.jpeg",
        title: "Terraforming Mars: Ares Expedition",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMarsColonies.jpeg",
        title: "Terraforming Mars: Colonies",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terrorBelow.jpeg",
        title: "Terror Below",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/terrorBelowHiddenCache.jpeg",
        title: "Terror Below: Hidden Cache",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/terrorInMeepleCity.webp",
        title: "Terror in Meeplecity",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/theArrival.avif", 
        title: "The Arrival", 
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/theCrewMissionDeepSea.webp",
        title: "The Crew: Mission Deep Sea",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theFoxInTheForest.webp",
        title: "The Fox in the Forest",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theIsleOfCats.jpeg",
        title: "The Isle of Cats",
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/theQuacksOfQuedlinburg.jpeg",
        title: "The Quacks of Quedlinburg",
        description: "TBA",
        storageLocation: "2nd Shelf Locker C",
    },
    { 
        imagePath: "./src/assets/gamePhotos/theRepublicOfRome.jpeg", 
        title: "The Republic of Rome", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/theResistance.jpeg",
        title: "The Resistance",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theSearchForPlanetX.jpeg",
        title: "The Search for Planet X",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/theTeaDragonSociety.jpeg",
        title: "The Tea Dragon Society",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/ticketToRide.jpeg",
        title: "Ticket To Ride",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/ticketToRideUnitedKingdom.webp",
        title: "Ticket To Ride: United Kingdom",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/tigrisAndEuphrates.jpeg",
        title: "Tigris & Euphrates",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/timeStories.jpeg",
        title: "Time Stories",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/tomorrow.jpeg", 
        title: "Tomorrow", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/trains.jpeg",
        title: "Trains",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/trajan.webp",
        title: "Trajan",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/trickerion.jpeg",
        title: "Trickerion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/tuscanyEssentialEdition.jpeg",
        title: "Tuscany: Essential Edition",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/twilightImperiumRex.webp",
        title: "Twilight Imperium Rex: Final Days of an Empire",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/twilightInscription.jpeg",
        title: "Twilight Inscription",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/twoRoomsAndABoom.jpeg",
        title: "Two Rooms and a Boom",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/tzokin.webp",
        title: "Tzolk'In",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/underwaterCities.jpeg",
        title: "Underwater Cities",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/underwaterCitiesNewDiscoveries.jpeg",
        title: "Underwater Cities: New Discoveries",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/unfair.jpeg",
        title: "Unfair",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/unlock.jpeg",
        title: "Unlock!",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/unlockSecretAdventuresANosideStory.jpeg",
        title: "Unlock! Secret Adventures: A Noside Story",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/unlockSecretAdventuresTheAdventuresOfOz.webp",
        title: "Unlock! Secret Adventures: The Adventures of Oz",
        description: "TBA",
        storageLocation: "4th Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/uno.jpeg",
        title: "Uno",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/vastTheCrystalCaverns.webp",
        title: "Vast: The Crystal Caverns",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/villainous.jpeg",
        title: "Villainous",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/viticulture.webp",
        title: "Viticulture",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/wanderingTowers.jpeg", 
        title: "Wandering Towers", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/warChest.jpeg",
        title: "War Chest",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/warOfWhispers.jpeg", 
        title: "War of Whispers", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/wastelandExpress.jpeg",
        title: "Wasteland Express",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/waterfallPark.jpeg", 
        title: "Waterfall Park", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/watergate.jpeg",
        title: "Watergate",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/wavelength.jpeg", 
        title: "Wavelength", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/weDidntPlaytestThisAtAll.jpeg",
        title: "We Didn't Playtest This at All",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/welcomeToYourPerfectHome.jpeg",
        title: "Welcome to Your Perfect Home",
        description: "TBA",
        storageLocation: "Top Drawer Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/werewords.webp",
        title: "Werewords",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/wingspan.jpeg",
        title: "Wingspan",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/wingspanAsia.webp",
        title: "Wingspan: Asia",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/witsAndWagers.jpeg", 
        title: "Wits & Wagers", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/worldsFair1893.jpeg",
        title: "World's Fair: 1893",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/yetiInMySpaghetti.avif", 
        title: "Yeti in My Spaghetti", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker C",
    },
    {
        imagePath: "./src/assets/gamePhotos/zombieDice.jpeg",
        title: "Zombie Dice",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
]

export default games_database;