
const descriptions = {
    fiveMinuteDungeon: "5-­Minute Dungeon is a chaotic, co-­operative, real-­time card game in which players have only five minutes to escape the randomized dungeon. Communication and teamwork are critical to survival because there's no time to form a carefully considered plan — and no predicting what dangers lie ahead.",
    sevenWonders: "You are the leader of one of the 7 great cities of the Ancient World. Gather resources, develop commercial routes, and affirm your military supremacy. Build your city and erect an architectural wonder which will transcend future times.",
    sevenWondersDuel: "In many ways 7 Wonders Duel resembles its parent game 7 Wonders. Over three ages, players acquire cards that provide resources or advance their military or scientific development in order to develop a civilization and complete wonders. What's different about 7 Wonders Duel is that, as the title suggests, the game is solely for two players.",
    sevenWondersDuelPantheon: "A pantheon from several civilizations — including Greek, Egyptian, and Middle-Eastern — gets added to 7 Wonders Duel in 7 Wonders Duel: Pantheon, with each god having its own power to help you or hinder your opponent.",
    aboveAndBelow: "Above and Below is a mashup of town-building and storytelling where you and up to three friends compete to build the best village above and below ground. In the game, you send your villagers to perform jobs like exploring the cave, harvesting resources, and constructing houses. Each villager has unique skills and abilities, and you must decide how to best use them.",
    agathaChristieDeathOnTheCards: "In Agatha Christie: Death on the Cards, which consists of a deck of eighty cards, players work co-operatively to solve a murder, using their detective skills to unmask the culprit and prevent their escape. The twist is that one of the players is the murderer and must work against the group to keep themselves hidden. Players also have dark secrets from their past they want to keep hidden from the other players. Who can you trust?",
    agricola: "In Agricola, you're a farmer in a wooden shack with your spouse and little else. At first, on a turn, your family gets to take only two actions, one for you and one for your spouse, as might be found among all the possibilities on a farm: plowing fields; collecting materials; building fences, and so on. There are numerous choices available, and while the game progresses you'll have more and more, as each round a new action card is flipped over, offering one more possible action. You might think about having kids in order to get more work accomplished but first you'll need to expand your house to make room - and what are you going to feed all the little rug rats?",
    airLandAndSea: "As Supreme Commander of your country's military forces in Air, Land, & Sea, you must carefully deploy your forces across three theaters of war: air, land, and sea. Air, Land, & Sea: Critters at War features the same gameplay as in Air, Land, & Sea, but with 100% critters and more vibrant colors.",
    alhambra: "Granada, 1278. At the foot of the Sierra Nevada mountains, one of the most exciting and interesting project of the Spanish Middle Ages begins: the construction of the ALHAMBRA. In Alhambra, players are acquiring buildings to be placed within their Alhambra complex.",
    alienFrontiers: "Do you have what it takes to be a deep space colonist? An alien frontier awaits the brave and daring! This new planet will be harsh, but if you have the skills to manage your resources, build a fleet, research alien life, and settle colonies, the world can be yours. Alien Frontiers is a game of resource management and planetary development for two to four players. During the game you will utilize orbital facilities and alien technology to build colony domes in strategic locations to control the newly discovered world.",
    amerigo: "In Amerigo, the players help Amerigo Vespucci on his journey to discover new land. The players explore the islands of South America, secure trading routes, and build settlements.",
    amongTheStars: "Among the Stars takes place in a war-ravaged galaxy where the warring alien races have declared peace in the wake of a threat with the potential to destroy them all. An Alliance is established to build space stations throughout the galaxy in order to promote trade among the races, strengthen diplomatic relations, and defend against this impending threat. Each player takes the role of one of those races trying to build the greatest space station. Through card drafting, the players select locations, and use these to build their station, scoring victory points based on the placement. The construction lasts four years, and the alien race with the most points at the end wins.",
    amunRe: "In Amun-Re, each pharaoh wants to build the most pyramids. To accomplish this, they must first acquire a province where they can trade and farm. With their profits, they can buy new provinces and building stones to erect pyramids. For all their actions, players must make clever use of their power cards and always offer appropriate sacrifices to Amun-Re.",

}

export default descriptions;