{/* Check which Fallout game we have. Goes in Top Shelf Locker B */}


const games_database = [
    {
        imagePath: "./src/assets/gamePhotos/7wonders.webp",
        title: "7 Wonders",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/aboveAndBelow.jpeg",
        title: "Above and Below",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/alhambra.jpeg",
        title: "Alhambra",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/alienFrontiers.webp",
        title: "Alien Frontiers",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/amunRe.webp",
        title: "Amun-Re",
        description: "TBA",
        storageLocation: "Top Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/arboretum.jpeg",
        title: "Arboretum",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkhamHorror.webp",
        title: "Arkham Horror",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/arkhamHorrorDunwich.jpeg",
        title: "Arkham Horror: The Dunwich Legacy",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/automobiles.png",
        title: "Automobiles",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/battlestarGalactica.jpeg",
        title: "Battlestar Galactica",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/betweenTwoCastlesOfMadKingLudwig.jpeg",
        title: "Between Two Castles of Mad King Ludwig",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/botc.webp",
        title: "Blood on the Clocktower", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/bloodRage.webp",
        title: "Blood Rage",
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bohnanza.jpeg",
        title: "Bohnanza",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/bulletStar.jpeg",
        title: "Bullet Star",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bunnyKingdom.jpeg",
        title: "Bunny Kingdom",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/bunnyKingdomInTheSky.webp",
        title: "Bunny Kingdom in the Sky",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/captainSonar.webp",
        title: "Captain Sonar",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/castlesOfMadKingLudwig.jpeg",
        title: "Castles of Mad King Ludwig",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/catInTheBox.webp",
        title: "Cat In The Box",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/championsOfMidgard.webp",
        title: "Champions of Midgard",
        description: "TBA",
        storageLocation: "4th Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cityOfGears.jpeg", 
        title: "City of gears", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cityOfIron.jpeg", 
        title: "City of Iron", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/clank.jpeg", 
        title: "Clank!", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/cockroachPoker.jpeg",
        title: "Cockroach Poker",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/Codenames.webp",
        title: "Codenames",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/concept.jpeg", 
        title: "Concept", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/cosmicEncounter.jpeg", 
        title: "Cosmic Encounter", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/coup.jpeg",
        title: "Coup",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/daybreak.jpeg", 
        title: "Daybreak", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker G-Left",
    },
    { 
        imagePath: "./src/assets/gamePhotos/deadOfWinter.webp", 
        title: "Dead of Winter", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/deckOfCards.jpeg",
        title: "Decks of Cards",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/decorum.jpeg", 
        title: "Décorum", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/dinosaurIsland.jpeg", 
        title: "Dinosaur Island", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/dixitOdyssey.png", 
        title: "Dixit: Odyssey", 
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/dominion.webp",
        title: "Dominion",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionAllies.jpeg",
        title: "Dominion: Allies",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionDarkAges.jpeg",
        title: "Dominion: Dark Ages",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/dominionSeaside.webp",
        title: "Dominion: Seaside",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F"
    },
    { 
        imagePath: "./src/assets/gamePhotos/dune.webp", 
        title: "Dune", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/duneImperium.jpeg", 
        title: "Dune: Imperium", 
        description: "TBA",
        storageLocation: "Bottom Shelf Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/eldritchHorror.jpeg",
        title: "Eldritch Horror",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left"
    },
    {
        imagePath: "./src/assets/gamePhotos/eldritchHorrorMountainsOfMadness.png",
        title: "Eldritch Horror: Mountains of Madness",
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left"
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdell.jpeg", 
        title: "Everdell", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdellBellfaire.jpeg", 
        title: "Everdell: Bellfaire", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/everdellNewLeaf.jpeg", 
        title: "Everdell: New Leaf", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/evolution.jpeg", 
        title: "Evolution", 
        description: "TBA",
        storageLocation: "Below Drawers Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/explodingKittens.jpeg", 
        title: "Exploding Kittens", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/forestShuffle.webp", 
        title: "Forest Shuffle", 
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/fromage.jpeg",
        title: "Fromage", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/funemployed.jpeg", 
        title: "Funemployed", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/furyOfDracula.webp", 
        title: "Fury of Dracula", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/gameOfThrones.webp", 
        title: "Game of Thrones", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/hanabi.jpeg", 
        title: "Hanabi", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/heat.jpeg", 
        title: "Heat: Pedal to the Metal", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/incanGold.png",
        title: "Incan Gold",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/jenga.jpeg",
        title: "Jenga",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/justOne.jpeg",
        title: "Just One",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/lemonadeStand.jpeg",
        title: "Lemonade Stand",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/letterJam.jpeg",
        title: "Letter Jam",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/lettersFromWhitechapel.png", 
        title: "Letters from Whitechapel", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/libertalia.webp", 
        title: "Libertalia", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/loveLetterPrincessPrincessEverAfter.jpeg",
        title: "Love Letter: Princess Princess Ever After",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/memoir44.webp",
        title: "Memoir '44",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/miceAndMystics.webp",
        title: "Mice & Mystics",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/mysterium.jpeg", 
        title: "Mysterium", 
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/mysticPaths.jpeg",
        title: "Mystic Paths",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/noThanks.jpeg",
        title: "No Thanks!",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/oceans.jpeg",
        title: "Oceans",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/oneNightUltimateWerewolf.webp",
        title: "One Night Ultimate Werewolf",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/pandemicIberia.jpeg",
        title: "Pandemic: Iberia",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/pandemicOnTheBrink.webp",
        title: "Pandemic: On the brink",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/paranormalDetectives.jpeg",
        title: "Paranormal Detectives",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/planes.jpeg",
        title: "Planes",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/planet.jpeg",
        title: "Planet",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/potionExplosion.png",
        title: "Potion Explosion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/puertoRico.jpeg",
        title: "Puerto Rico",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/railroadInkChallenge.png",
        title: "Railroad Ink Challenge",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/rollForTheGalaxy.png",
        title: "Roll for the Galaxy",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    { 
        imagePath: "./src/assets/gamePhotos/saboteur.jpeg", 
        title: "Saboteur", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/santorini.jpeg",
        title: "Santorini",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/Scout.jpeg", 
        title: "Scout", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/Set.webp", 
        title: "Set", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/shadowsOverCamelot.webp",
        title: "Shadows Over Camelot",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F"
    },
    {
        imagePath: "./src/assets/gamePhotos/skull.jpeg",
        title: "Skull",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/slayTheSpire.jpeg", 
        title: "Slay the Spire", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/soClover.jpeg",
        title: "So Clover",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    { 
        imagePath: "./src/assets/gamePhotos/spiritIsland.webp",
        title: "Spirit Island", 
        description: "TBA",
        storageLocation: "3rd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/spiritIslandFeatherAndFlame.webp",
        title: "Spirit Island: Feather and Flame",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/stardewValley.jpeg",
        title: "Stardew Valley",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/subdivision.webp",
        title: "Subdivision",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/suburbia.jpeg",
        title: "Suburbia",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/sushiGo.png", 
        title: "Sushi Go!", 
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/sushiGoParty.webp",
        title: "Sushi Go Party!",
        description: "TBA",
        storageLocation: "Bottom Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/takenoko.jpeg",
        title: "Takenoko",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMars.jpeg",
        title: "Terraforming Mars",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMarsAresExpedition.jpeg",
        title: "Terraforming Mars: Ares Expedition",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terraformingMarsColonies.jpeg",
        title: "Terraforming Mars: Colonies",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/terrorInMeepleCity.webp",
        title: "Terror in Meeplecity",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    { 
        imagePath: "./src/assets/gamePhotos/theArrival.avif", 
        title: "The Arrival", 
        description: "TBA",
        storageLocation: "2nd Shelf Locker G-Left",
    },
    {
        imagePath: "./src/assets/gamePhotos/theCrewMissionDeepSea.webp",
        title: "The Crew: Mission Deep Sea",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theFoxInTheForest.webp",
        title: "The Fox in the Forest",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theIsleOfCats.jpeg",
        title: "The Isle of Cats",
        description: "TBA",
        storageLocation: "Top Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/theResistance.jpeg",
        title: "The Resistance",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/theSearchForPlanetX.jpeg",
        title: "The Search for Planet X",
        description: "TBA",
        storageLocation: "2nd Shelf Locker B",
    },
    {
        imagePath: "./src/assets/gamePhotos/theTeaDragonSociety.jpeg",
        title: "The Tea Dragon Society",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/ticketToRide.jpeg",
        title: "Ticket To Ride",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/ticketToRideUnitedKingdom.webp",
        title: "Ticket To Ride: United Kingdom",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/tigrisAndEuphrates.jpeg",
        title: "Tigris & Euphrates",
        description: "TBA",
        storageLocation: "Top Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/timeStories.jpeg",
        title: "Time Stories",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/trains.jpeg",
        title: "Trains",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/trickerion.jpeg",
        title: "Trickerion",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/twilightImperiumRex.webp",
        title: "Twilight Imperium Rex: Final Days of an Empire",
        description: "TBA",
        storageLocation: "Bottom Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/tzokin.webp",
        title: "Tzolk'In",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/underwaterCities.jpeg",
        title: "Underwater Cities",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/underwaterCitiesNewDiscoveries.jpeg",
        title: "Underwater Cities: New Discoveries",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/unfair.jpeg",
        title: "Unfair",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/uno.jpeg",
        title: "Uno",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/villainous.jpeg",
        title: "Villainous",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/wastelandExpress.jpeg",
        title: "Wasteland Express",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/weDidntPlaytestThisAtAll.jpeg",
        title: "We Didn't Playtest This at All",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/werewords.webp",
        title: "Werewords",
        description: "TBA",
        storageLocation: "2nd Drawer Locker G-Right",
    },
    {
        imagePath: "./src/assets/gamePhotos/wingspan.jpeg",
        title: "Wingspan",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/wingspanAsia.webp",
        title: "Wingspan: Asia",
        description: "TBA",
        storageLocation: "2nd Shelf Locker F",
    },
    {
        imagePath: "./src/assets/gamePhotos/zombieDice.jpeg",
        title: "Zombie Dice",
        description: "TBA",
        storageLocation: "Top Drawer Locker G-Right",
    },
]

export default games_database;